name: Update File

on:
  push:
    branches:
      - main
  # pull_request:
  pull_request_target:
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # changed files back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write

    steps:
    - uses: actions/checkout@v3
      # if: github.event_name === 'pull_request_target'
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}

    # - uses: actions/checkout@v3
    #   if: github.event_name !== 'pull_request_target'
    #   with:
    #     ref: ${{ github.head_ref }}

    - run: echo - $(date +%Y-%m-%d-%H-%M-%S) >> file-to-update.md

    - name: wip
      id: date_convert
      run: |
        TIMESTAMP_OF_LAST_COMMIT=$(git log -1 --date=unix --format=%ad);
        FORMATED_DATE=$(date -u -d @$TIMESTAMP_OF_LAST_COMMIT +%Y-%m-%d)

        # Convert timestamp to UTC date in Y-m-d format
        echo "date=$(echo $FORMATED_DATE)" >> $GITHUB_OUTPUT;

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        commit_message: Commit made through git-auto-commit ${{ steps.date_convert.outputs.date }}

    - name: "Run if changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 1
      run: echo "Changes!"

    - name: "Run if no changes have been detected (bool)"
      if: ${{ steps.commit.outputs.changes_detected }} == 0
      run: echo "No Changes!"

    - name: GITHUB_OUTPUT value
      run: echo $GITHUB_OUTPUT
